### ISSUE TITLE
badge visual is moved to the wrong visual-frame when editing a badge

### ISSUE THREAD

**Issue by Annicelia** [mint-o-badges/badgr-ui#361]
if you click on “edit” to edit an existing badge, the badge image slips into the wrong frame (“Unseren Editor nutzen”) and therefore the additional badge-frame is added unnecessarily.

![Bildschirmfoto 2024-05-28 um 15 12 36](https://github.com/mint-o-badges/badgr-ui/assets/164371483/8264e51c-b0bb-4ea0-ba3b-43bccd6444c6)

**Comment by zven** [comment]
@jona159 Is that maybe also related to https://github.com/mint-o-badges/badgr-ui/issues/359 and already fixed? 🤔

**Comment by YouQam** [comment]
It is fixed now as I couldn't reproduce the issue.

**Comment by jona159** [comment]
> It is fixed now as I couldn't reproduce the issue.

@YouQam for me the issue still persists, how did you test this?

**Comment by YouQam** [comment]
> > It is fixed now as I couldn't reproduce the issue.
> 
> [@YouQam](https://github.com/YouQam) for me the issue still persists, how did you test this?

@jona159 You are right. I just tested uploading an image in `Eigenes Visual nutzen` and was expecting it to move to `Unseren Editor nutzen` but it seems that the issue is the other way around.
